---
editor:
  name: "jessitron.elm-rugs.Organize"
  group: "jessitron"
  artifact: "elm-rugs"
  version: "1.0.3"
  origin:
    repo: "git@github.com-personal:jessitron/elm-rugs.git"
    branch: "master"
    sha: "3782bb3*"
  parameters:
    - "project_name": "Yow"

---
editor:
  name: "jessitron.elm-rugs.AddImport"
  group: "jessitron"
  artifact: "elm-rugs"
  version: "1.0.3"
  origin:
    repo: "git@github.com-personal:jessitron/elm-rugs.git"
    branch: "master"
    sha: "3782bb3*"
  parameters:
    - "module_to_import": "Html.Attributes"

---
editor:
  name: "jessitron.elm-rugs.UpgradeToBeginnerProgram"
  group: "jessitron"
  artifact: "elm-rugs"
  version: "1.0.3"
  origin:
    repo: "git@github.com-personal:jessitron/elm-rugs.git"
    branch: "master"
    sha: "3782bb3*"
  parameters:

---
editor:
  name: "jessitron.elm-rugs.AddTextInput"
  group: "jessitron"
  artifact: "elm-rugs"
  version: "1.0.3"
  origin:
    repo: "git@github.com-personal:jessitron/elm-rugs.git"
    branch: "master"
    sha: "3782bb3*"
  parameters:
    - "input_name": "newLabel"

---
editor:
  name: "jessitron.elm-rugs.OnEnter"
  group: "jessitron"
  artifact: "elm-rugs"
  version: "1.0.3"
  origin:
    repo: "git@github.com-personal:jessitron/elm-rugs.git"
    branch: "master"
    sha: "3782bb3*"
  parameters:
    - "enter_message": "SaveLabel"

---
editor:
  name: "jessitron.elm-rugs.UpgradeToProgram"
  group: "jessitron"
  artifact: "elm-rugs"
  version: "1.0.3"
  origin:
    repo: "git@github.com-personal:jessitron/elm-rugs.git"
    branch: "master"
    sha: "3782bb3*"
  parameters:

---
editor:
  name: "jessitron.elm-rugs.SubscribeToClicks"
  group: "jessitron"
  artifact: "elm-rugs"
  version: "1.0.3"
  origin:
    repo: "git@github.com-personal:jessitron/elm-rugs.git"
    branch: "master"
    sha: "3782bb3*"
  parameters:

---
editor:
  name: "jessitron.elm-rugs.FocusCommand"
  group: "jessitron"
  artifact: "elm-rugs"
  version: "1.0.3"
  origin:
    repo: "git@github.com-personal:jessitron/elm-rugs.git"
    branch: "master"
    sha: "3782bb3*"
  parameters:

